### ISSUE TITLE
Container on DockerHub

### ISSUE THREAD

**Issue by ChiefAlexander** [ip-api/proxy#3]
Opening this issue to start the discussion about how we are wanting to have an official docker image on dockerhub (or some other container repo). Internally we use [goreleaser](https://goreleaser.com/) which does all of our heavy lifting for releasing our go projects.

**Comment by rysenko** [comment]
Is it available on Docker Hub now? I'd really want to use this proxy and it would be great if I could skip creating my own Dockerfile.

**Comment by ChiefAlexander** [comment]
I've pushed a build-out on my own dockerhub account if you want to use that `chiefalexander/ip-api-proxy`. There is not an official image yet.

**Comment by rysenko** [comment]
@ChiefAlexander Thank you for making this available. I'm using this for 5 days already in my stack under average load and seems good so far. I've also got rid of my own requests caching and rely on this image, usage stats in IP-API remained the same. Would be great to have this official eventually. But it is good as it is already.
